apiVersion: v1
kind: Service
metadata:
  namespace: labwordpress
  name: wordpress-service
  labels:
    app: wordpress
spec:
  selector:
    app: wordpress
  ports:
    - port: 80
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: labwordpress
  name: wordpress-pvclaim
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: labwordpress
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:latest
        ports:
        - containerPort: 80
        env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: labwordpress-configmap
              key: database-host
        - name: WORDPRESS_DB_USER
          valueFrom:
            configMapKeyRef:
              name: labwordpress-configmap
              key: database-user
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: WORDPRESS_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: labwordpress-configmap
              key: database-name
        volumeMounts:
        - name: wordpress-persistent-storage-lab
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage-lab
        persistentVolumeClaim:
          claimName: wordpress-pvclaim
